### ISSUE TITLE
Linking Names

### ISSUE THREAD

**Issue by cutic** [Thaerious/NERVE#57] opened 2016-05-04 20:25 UTC
Doesn't work at all. Documents tested: Cultural Mapping - Talk to the work and Preface. A window pops up but no options for linking and errors pop up.

**Comment by abramoffcwrc** [comment] 2016-05-04 20:26
![image](https://cloud.githubusercontent.com/assets/17013275/15028068/21b3880e-1204-11e6-94b8-5313aeb99db2.png)
![image](https://cloud.githubusercontent.com/assets/17013275/15028083/36be4b3a-1204-11e6-85bc-c317eabe666d.png)

**Comment by cutic** [comment] 2016-05-04 20:27
Orgnames produces the same error.

**Comment by Thaerious** [comment] 2016-05-04 20:45
I need clarification on "Doesn't work at all".  Or doesn't work in this case?  My guess it's the space in the query, which can be fixed but this ticket sounds way more ominous than that.  Does it work on other files? does it work on other links in this file?

**Comment by cutic** [comment] 2016-05-04 20:56
This HTTP Status 500 seems to appear in all documents we tested on both OS's, however it pops up randomly. In some cases you can get it to open the Geonames and Viaf and then it pops up, and after closing it you can link whatever it is you are trying to link. The last documents we tried doing this in were Preface and Foreword.

**Comment by SusanBrown** [comment] 2016-05-05 00:23
I had the same error appear when trying to link a name. This was using the file duncsa-short.xml.

After I got this I closed the error and got a links box that had CWRC and Geonames options but not VIAF. Then I chose another name "Byron" (i.e. no space) and got VIAF, and successfully added the link.
Then chose Ella Wheeler Wilcox and got the same error.

So the theory that the problem is the spaces is right.
Tested with orgname and same thing: it's the space between words.

![image](https://cloud.githubusercontent.com/assets/545952/15032989/721be360-1234-11e6-9e29-c8d5a6a1c69c.png)

**Comment by Thaerious** [comment] 2016-05-06 14:03
I have uploaded a fix for viaf lookups.  I couldn't find the "daniel laforest" in the specified document, though I tested it with other space containing names.  Try it again and let me know if it problem persists.  This 'should' also work with other special characters.

**Comment by SusanBrown** [comment] 2016-05-06 14:50
Hurray: the space problem is fixed across all entities. Didn’t text with special characters.

**Comment by Thaerious** [comment] 2016-05-06 14:56
I'm closing this ticket, feel free to reopen it if the issue reoccurs.

**Comment by cutic** [comment] 2016-05-16 21:13
VIAF doesn't show up when trying to link person names. Also, random errors pop up. (Salomania, Mac; PC)

**Comment by Thaerious** [comment] 2016-05-16 21:14
Which names in which document and what are the random errors?

**Comment by abramoffcwrc** [comment] 2016-05-16 21:18
It seems to be working now. We can't recreate the issues.

**Comment by Thaerious** [comment] 2016-05-16 21:21
This may be a recurring problem with the VIAF api, i'll have to wait for it to happen to me.

**Closed** 2016-05-17 13:35 UTC
Labels: bug - can not replicate, bug - high priority, test case
