### ISSUE TITLE
Firefox problem: NERVE takes you to other random websites. 

### ISSUE THREAD

**Issue by cutic** [Thaerious/NERVE#67] opened 2016-05-16 20:03 UTC
Mac and PC, documents used: Where are you From & Edmonton Pipeline

When you tag a word in the text pane and drag and drop it in the left hand box (any category) it takes you to a different website that has that word somewhere in it. 

E.g. I tagged the word "immigrants," and it took me to domainmarket.com (immigrants.com) (http://www.domainmarket.com/buynow/immigrants.com).

**Comment by Thaerious** [comment] 2016-05-16 20:13
that shouldn't happen
like, at all.

**Comment by Thaerious** [comment] 2016-05-16 20:57
I can not recreate this issue.  It sounds like it might be local to your machine, I would scan for adware.

**Comment by abramoffcwrc** [comment] 2016-05-16 21:05
We both had this issue (Mac and PC, just on Firefox) and we are both on lab computers. Here's how to recreate it. I used the document 6. Cultural Mapping - talk to the work - semantic tagging.
1. I highlighted a random word. For example, "translated."
2. I dragged this word over to the lemma bar to "Book Industry Study Group" under orgname.
3. The page loads and in the left hand corner it says "Connecting" for a few moments.
4. You end up on a random translation website.

**Comment by Thaerious** [comment] 2016-05-16 21:19
2.  Where did you drop it?  
a) in the white area
b) on the title bar
c) on another entity

3.  Left hand corner of the browser or computer?
4.  Is the site actually random, or the same every time?

I'm actually thinking that it is a local setup of some sort, auto translation software or something.  Forwarding pages like that isn't something you do by accident.

**Comment by abramoffcwrc** [comment] 2016-05-16 21:24
I dropped it right on top of the entity in the lemma panel. 
The site isn't completely random, because it takes you to a website that has some sort of link with the word. For example, if you drag and drop the word "immigration" it takes you to immigration.com. When I did it with the word "translation" it took me to a translation website. I accidentally did this with the word "hard" and it took me to a porn website!

**Comment by Thaerious** [comment] 2016-05-16 21:27
Try to recreate it on a different computer, this really smells like adware.

**Comment by ilovan** [comment] 2016-05-16 21:45
We just tried it on third and fourth computer, included mine of which I am fairly certain is malware free: it still does the exact same thing. If you drag the newly created entity over a lemma or a white space in the lemma panel you are automatically redirecting to a URL where the domain name has a strong match with the term you were dragging.

**Comment by Thaerious** [comment] 2016-05-17 13:33
Just to be pedantic, was the third and forth computers non-lab computers? 
We will have to set up a video-chat so I can see this occurring, as I have yet to reproduce it.

**Comment by SusanBrown** [comment] 2016-05-17 13:43
Tried to reproduce this and couldn’t because I couldn’t get highlighted entities to drag. On Mac, Chrome, cleared cache (the new layout and menu is a great improvement!)
Will create new ticket.

**Comment by SusanBrown** [comment] 2016-05-17 13:48
Using Ctrl M to first create the entity and trying a few time with different entities I could not reproduce this issue.

**Comment by Thaerious** [comment] 2016-05-17 14:26
changing the tag to low priority until I can reproduce.  (The red color sticks out on the screen so I can see them better).

**Comment by abramoffcwrc** [comment] 2016-05-17 15:51
I just reproduced this on my personal computer (PC on Firefox). I do not have malware and was not on the school's internet connection. 
To answer your question, the third computer was a lab computer, and the fourth computer was Mihaela's. 

This only occurs on Firefox. On PC I do not use ctrl M to create the entity before dragging it over. I just highlight a word and drag it over, and after a few seconds of loading another website pops up. I did it with the word "from" today. "from.com" popped up.

**Comment by SusanBrown** [comment] 2016-05-17 15:55
Can you please specify what you were selecting, whether you’re using Ctrl M or dragging and dropping? I tried it with the file you mentioned but didn’t know what exactly you were doing. Seems as if you need to Skype and share screens with Ed to show him this.
Is this happening all the time or just occasionally? Does it interfere with core functionality or is it an annoyance?

**Comment by abramoffcwrc** [comment] 2016-05-18 01:02
Susan, here's what I did in Firefox:
1. I highlighted a random word. For example, "translated."
2. I dragged this word over to the lemma bar to "Book Industry Study Group" under orgname and dropped it there (it doesn't really matter where as long as it's in the box).
3. The page loads and in the left hand corner it says "Connecting" for a few moments.
4. You end up on a translation website.

This is happening all the time. I think it is a real problem, as it can take users to websites with malware/inappropriate websites. Also, it's not possible to tag things by dragging them over to the lemma bar if this is happening, so yes, I'd say it interferes with core functionality.

**Comment by Thaerious** [comment] 2016-05-18 01:59
So this is happening on both Mac and PCs?  And with which browser?  We'll need to skype this asap as I can't recreate the issue.  Also could you list a half dozen of the different websites that show up, I want to see if there is a pattern in the url.  If you are using chrome I'll need you to have the console window open when you show me.  Press F12 and click on console.

**Comment by Thaerious** [comment] 2016-05-18 02:04
So I just tried this on firefox, and now I can recreate it.  For the time being please use chrome, it's what the program has been developed on.  That being said, I'm going to get to the bottom of the firefox issue. This may take time.

**Comment by SusanBrown** [comment] 2016-05-18 02:06
Good that you were able to recreate it, and thanks for the additional info, Kristi.

And if we are just using it in-house, then we can ensure that everyone uses Chrome, so this is not a high-priority issue in terms of immediate usability, although it needs to be addressed in the long run. So please prioritize other issues.

**Comment by Thaerious** [comment] 2016-05-19 14:01
This will be put on the back-burner for the time being.  I attempted a fix for firefox but it is not co-operating.  I simply don't have to time right now to figure this one out.

**Comment by abramoffcwrc** [comment] 2016-05-19 14:12
Let me know if you want to Skype when you have time so I can show you this problem.

**Comment by SusanBrown** [comment] 2016-05-19 14:16
Kristi, let’s back burner this now as Ed says—best to just use Chrome for the time being. 

Could you do a thorough test of the basic functionality in Chrome, from upload through tagging and linking to download, and see if it seems usable? That would be extremely helpful!

**Comment by Thaerious** [comment] 2016-05-19 14:22
I know what the problem is, I don't know the fix yet.  So no skype necessary.

**Comment by abramoffcwrc** [comment] 2016-05-19 21:59
It's working properly now!

**Closed** 2016-06-02 19:46 UTC
Labels: bug - low priority
