### ISSUE TITLE
change URI in REF attribute

### ISSUE THREAD

**Issue by SusanBrown** [Thaerious/NERVE#47] opened 2016-04-30 04:26 UTC
The path at the start of the URIs being recorded in the REF attribute on the entity tags is wrong.

Current example:  http://cwrc-dev-01.srv.ualberta.ca/islandora/object/cwrc:a2ab03b6-371d-4d10-9cfd-bc705d7304f3

Corrected version of same entity: http://commons.cwrc.ca/cwrc:a2ab03b6-371d-4d10-9cfd-bc705d7304f3

**Comment by Thaerious** [comment] 2016-05-02 15:06
Hello Susan,

The problem is when a piece of text is being tagged but that text starts with
a tag.  The program expects the content to start with text, not a tag.  This
was an oversight and I'm fixing it now.  It shouldn't be too big of a fix, but
it's not tiny either.

Regards,
-Ed

Ed Armstrong
edward@sharcnet.ca | www.sharcnet.ca

----- Original Message -----

**Comment by Thaerious** [comment] 2016-05-04 20:48
This is (hopefully) fixed.

**Comment by SusanBrown** [comment] 2016-05-16 04:21
Entities URIs are still reading wrong:
Here's what's being saved for Ella Wheeler Wilcox:
http://cwrc-dev-01.srv.ualberta.ca/islandora/object/cwrc:a6669e12-7d13-421f-990e-8034804253bf
That is, this is what it says in the Link field in the Link popup. Downloading seems to be broken again so I can't check the file itself.

**Comment by jefferya** [comment] 2016-05-16 04:57
The cwrc-dev-01 server is currently down. That being said, this is a
development server and if NERVE is being used to create production
documents based on entities from this server, let me know asap
Susan/Mihaela/Michael.

**Comment by SusanBrown** [comment] 2016-05-16 05:01
Mihaela previously gave instructions for the right URI with the correct prefix, i.e. http://commons.cwrc.ca/cwrc: <http://commons.cwrc.ca/cwrc:>[PID]

**Comment by Thaerious** [comment] 2016-05-17 13:47
This is the URL I am using to acquire CWRC lookup results.  "http://beta.cwrc.ca/islandora/cwrc_entities/v1/search/", it returns a field called PID.  I append the search string to the PID to create the link URI that is stored in the file.  I have changed it to keep searching from beta.swrc.ca but now I append the PID to the following "http://commons.cwrc.ca/cwrc:".  This will be live later today.  

Regarding jefferya:  I'm not too sure what you mean, I'm not inserting any data to that address, but we are creating (editing) documents.

**Comment by SusanBrown** [comment] 2016-05-17 13:49
Sounds like all is well. Jeff just wanted to make sure you weren’t looking up in the wrong repo. Stick with beta ;)

**Comment by jefferya** [comment] 2016-05-17 14:43
All is good regarding my query! As Susan said, just checking some details
and all is fine regarding my query.

**Comment by Thaerious** [comment] 2016-06-02 19:45
Here is an example tag that I linked 
<NAME STANDARD="Leanna Brodie" annotationid="ent_70831" ref="http://commons.cwrc.ca/cwrc:cwrc:f06f6024-22ac-4e2d-bfe2-01c113d8b461">Leanna Brodie</NAME>
It now has commons....
Closing the ticket for now.

**Closed by Thaerious** 2016-06-02 19:45 UTC
Labels: test case
