### ISSUE TITLE
FenwickBioTest1: DecoderException

### ISSUE THREAD

**Issue by SusanBrown** [Thaerious/NERVE#85] opened 2016-05-23 21:16 UTC
Also produced when try to download after minimal tagging; looks like it has to do with area tag.

Produced with FenwickBioTest1

ca.sharcnet.nerve.fileservices.decode.DecoderException

The element type "area" must be terminated by the matching end-tag "".

cause: org.xml.sax.SAXParseException

cause: The element type "area" must be terminated by the matching end-tag "".

com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:257)

com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:348)

javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:121)

ca.sharcnet.nerve.fileservices.decode.FormatDecoder.decode(FormatDecoder.java:60)

ca.sharcnet.nerve.fileservices.Restore.processRequest(Restore.java:114)

ca.sharcnet.nerve.fileservices.accounts.abstractservlets.CustomServlet.doPost(CustomServlet.java:122)

javax.servlet.http.HttpServlet.service(HttpServlet.java:648)

javax.servlet.http.HttpServlet.service(HttpServlet.java:729)

org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291)

org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)

org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)

org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)

org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)

org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:217)

org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)

org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)

org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142)

org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)

org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:616)

org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)

org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:518)

org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1091)

org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:673)

org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1500)

org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1456)

java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)

java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)

org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)

java.lang.Thread.run(Thread.java:745)

**Comment by Thaerious** [comment] 2016-05-24 14:02
I am not getting a decoder exception on this file.  However 2 other issues I'm hijacking this ticket for.  1) It is throwing a JavaScriptException when I open it, I thought I had squashed those.  2)decoder exceptions are typically malformed xml exceptions, and I want the app to report them better.  Note that with malformed xml exceptions there is little I can do about them for the short term, that's a MUCH bigger project and unless I can find a different xml parsing library it's beyond scope.  But I do want to report them better.

**Comment by SusanBrown** [comment] 2016-05-24 14:16
I’d be surprised if it wasn’t well-formed XML but it’s possible. 

A clear message saying that this was the problem would be helpful for sure.

We will try to do some much more systematic coding today to get some more clarity on things.

There are a number of things going on and I think we need some careful evaluation of where they are at. 

1) Thing are being complicated by different schema types (we made a mistake in focusing so much on TEI files only for so long—the CWRC and Orlando schemas are definitely having problems more than the TEI one)

2) Things are complicated by whether files have been used in the CWRC-Writer before (I think this is causing problems in and of itself, though the recent changes to the schemas may have helped or eliminated these, I haven’t had time to check)

We need to systematically check the various permutations and combinations:

**Comment by jefferya** [comment] 2016-05-24 14:56
To add to the list of general things to check:

(1) check for invalid characters (i.e. non-UTF-8) characters

Some of the exceptions could be caused bythe doc containing non-UTF-8
characters. This can happen during copy-paste or editing in MS Word and
then using the Orlando Doc Archive check-in, for example. CWRC-Writer and
the repository, have both been tested with UTF-8 making sure neither
mangles the UTF-8 characters (e.g., like the Doc Archive does with any
characters that is not on the keyboard)?


(2) UTF-8 characters

Some of the exceptions could be caused by NERVE not properly handling
UTF-8. One could try a very small, hand crafted doc to test very specific
cases.


My 2 cents.

Cheers,
~Jeff

**Comment by Thaerious** [comment] 2016-05-24 15:12
It's not UTF-8  I believe I have caught all of those, but I don't think it has been tested.  It is likely the conversion from xml to html.  There are differences in self closing tags between the two markups.  I was getting around it by making sure all tags had some content, but it's more of a hack than a fix.  I am going to look into this one deeper when I can.  I have two sharcnet official events to prepare for that is pressing on my time.

**Comment by Thaerious** [comment] 2016-05-31 20:45
The next push fixes a number of downloading errors.  To test it reupload the file and then try downloading again.

**Comment by Thaerious** [comment] 2016-06-02 19:30
Moving this to https://github.com/Thaerious/NERVE/issues/92

**Closed by Thaerious** 2016-06-02 19:30 UTC
Labels: bug - low priority
